#!/bin/bash
set -e

cd /workspace

# Запуск тестов через Maven
mvn -B clean test -Dgroups=Second -DsuiteXmlFile='src/test/resources/StartNodes.xml' \
    -DPASSWORD="$DPASSWORD" -DPIN="$DPIN" \
    -DSEED_PHRASE_10="$DSEED_PHRASE_10" -DEMAIL_10="$DEMAIL_10" \
    -DSEED_PHRASE_9="$DSEED_PHRASE_9" -DEMAIL_9="$DEMAIL_9" \
    -DSEED_PHRASE_8="$DSEED_PHRASE_8" -DEMAIL_8="$DEMAIL_8" \
    -DSEED_PHRASE_7="$DSEED_PHRASE_7" -DEMAIL_7="$DEMAIL_7" \
    -DSEED_PHRASE_6="$DSEED_PHRASE_6" -DEMAIL_6="$DEMAIL_6" \
    -DSEED_PHRASE_5="$DSEED_PHRASE_5" -DEMAIL_5="$DEMAIL_5" \
    -DSEED_PHRASE_4="$DSEED_PHRASE_4" -DEMAIL_4="$DEMAIL_4" \
    -DSEED_PHRASE_3="$DSEED_PHRASE_3" -DEMAIL_3="$DEMAIL_3" \
    -DSEED_PHRASE_2="$DSEED_PHRASE_2" -DEMAIL_2="$DEMAIL_2" \
    -DSEED_PHRASE_1="$DSEED_PHRASE_1" -DEMAIL_1="$DEMAIL_1" \
    -DSEED_PHRASE_0="$DSEED_PHRASE_0" -DEMAIL_0="$DEMAIL_0"