name: MonadScore CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISPLAY: :99
      SEED_10: ${{ secrets.SEED_PHRASE_10 }}
      MAIL_10: ${{ secrets.EMAIL_10 }}
      SEED_9: ${{ secrets.SEED_PHRASE_9 }}
      MAIL_9: ${{ secrets.EMAIL_9 }}
      SEED_8: ${{ secrets.SEED_PHRASE_8 }}
      MAIL_8: ${{ secrets.EMAIL_8 }}
      SEED_7: ${{ secrets.SEED_PHRASE_7 }}
      MAIL_7: ${{ secrets.EMAIL_7 }}
      SEED_6: ${{ secrets.SEED_PHRASE_6 }}
      MAIL_6: ${{ secrets.EMAIL_6 }}
      SEED_5: ${{ secrets.SEED_PHRASE_5 }}
      MAIL_5: ${{ secrets.EMAIL_5 }}
      SEED_4: ${{ secrets.SEED_PHRASE_4 }}
      MAIL_4: ${{ secrets.EMAIL_4 }}
      SEED_3: ${{ secrets.SEED_PHRASE_3 }}
      MAIL_3: ${{ secrets.EMAIL_3 }}
      SEED_2: ${{ secrets.SEED_PHRASE_2 }}
      MAIL_2: ${{ secrets.EMAIL_2 }}
      SEED_1: ${{ secrets.SEED_PHRASE_1 }}
      MAIL_1: ${{ secrets.EMAIL_1 }}
      SEED_0: ${{ secrets.SEED_PHRASE_0 }}
      MAIL_0: ${{ secrets.EMAIL_0 }}
      PASS: ${{ secrets.PASSWORD }}
      PIN: ${{ secrets.PIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build Docker image
        run: docker build -t ci-chrome138:latest .

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e DISPLAY=$DISPLAY \
            -e SEED_10="$SEED_10" -e MAIL_10="$MAIL_10" \
            -e SEED_9="$SEED_9" -e MAIL_9="$MAIL_9" \
            -e SEED_8="$SEED_8" -e MAIL_8="$MAIL_8" \
            -e SEED_7="$SEED_7" -e MAIL_7="$MAIL_7" \
            -e SEED_6="$SEED_6" -e MAIL_6="$MAIL_6" \
            -e SEED_5="$SEED_5" -e MAIL_5="$MAIL_5" \
            -e SEED_4="$SEED_4" -e MAIL_4="$MAIL_4" \
            -e SEED_3="$SEED_3" -e MAIL_3="$MAIL_3" \
            -e SEED_2="$SEED_2" -e MAIL_2="$MAIL_2" \
            -e SEED_1="$SEED_1" -e MAIL_1="$MAIL_1" \
            -e SEED_0="$SEED_0" -e MAIL_0="$MAIL_0" \
            -e PASS="$PASS" \
            -e PIN="$PIN" \
            -v ${{ github.workspace }}:/workspace \
            -v ~/.m2:/root/.m2 \
            ci-chrome138:latest \
            bash /workspace/run-tests.sh

      - name: Upload screen recording
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screen-recording
          path: target/allure-results/screen_recording.mp4

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
